### ISSUE TITLE
Child Bridges support

### ISSUE THREAD

**Issue by Bladestar2105** [rpolenthon/homemanagerapp#3]
Hello,

first of all, your app rocks 😁👌
I think you know for the new child bridge feature of homebridge beta 1.3.0. Can you please add support for this in your app so we can restart child instances indepentend from the main instance?
This would be great 🙂

More information here: https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by rpolenthon** [comment]
Hi @Bladestar2105,

first of all, very nice to hear that you like the app.

We are aware of the child bridges and follow the development closely. We will definitely implement child bridges into the app. This might not be with the next one or two releases, as features as iOS 14 Widgets were requested dozens of times and need to/should be implemented first.

I will close this issue here as "Child Bridge" support is definitely planned for a further release (maybe at the beginning of Q2).

If there is anything else you would like to see in the app, write us a mail to info@homemanager-app.de

Cheers,
Ron
